create wifiLED
SchooMyDevelopment/schoomy_board pull request #1
Opened 2022-04-13 07:44 UTC by syunsukefujisawa-schoomy

ベースのwifi経由でLEDを制御するプログラムの
HTMLのテキスト、シリアルモニタのログを日本語化がメイン

2022-04-13 09:36 UTC, ryoimayoshi-schoomy requested changes
@syunsukefujisawa-schoomy 
さらっと目を通しました！ご確認よろしくお願いします。

2022-04-13 09:36 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +#define SPI_SPEED   115200
スクーミー的にSPI_SPEEDは定義せずそのままSerial.beginに突っ込みましょうか。

2022-04-13 09:36 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +    Serial.print("IPアドレス: ");
ここで表示されるIPアドレスにhttp接続すると上のhtmlの画面が表示されるんですよね？
であればユーザビリティを考えるとシリアルモニタに「http://{ip}にアクセスしてください。」
みたいな表示をしてもよいかなと思いますね。

2022-04-13 09:36 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +  <head>
キッチリ作るならtitleも入れたほうがいいかもですね。
もし今後このコードをスクーミー公式で使用するのであればデザインも気になるけど・・・このPRでそこまでやってるとキリないので今回はいいかなｗ
いずれかのタイミングで対応しましょうか。

もしtitleを入れるなら下で使ってるPAGE_TITLEを変数化してそれを使いまわしてください！

2022-04-13 09:36 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +    // モニターにローカル IPアドレスを表示する
このコメントはコードを見ればわかるので削除してください。
パッと見ましたがコメントは全削除でよいです。

2022-04-14 02:20 UTC, naokiito-schoomy commented on black/sketch/wifi_LED.ino
> +String measuredString = "";
String measuredString = "";    
これは使っていないので無くてもよさそうですね

2022-04-14 04:06 UTC, naokiito-schoomy approved these changes

2022-04-14 04:07 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +
確認した箇所は消しました

2022-04-14 04:07 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +  <head>
HTMLで変数を扱う方法が分からなかったので一旦下のPAGE_TITLEと同じ方法で後からbufに入れてreplaceしました。必要ならここは変えます。

2022-04-14 04:07 UTC, naokiito-schoomy commented
確認しました。
動作としては問題ありません。

2022-04-14 04:07 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +void setup() {
最後に回しました。

2022-04-14 04:08 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +
確認した箇所は消しました

2022-04-14 04:08 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +String measuredString = "";
そうですね。使っていなかったので消しました。

2022-04-14 04:08 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +#define SPI_SPEED   115200
変更しました。

2022-04-14 04:09 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +    Serial.print("IPアドレス: ");
「http://{ip}にアクセスしてください」になるようにしました。

2022-04-14 04:09 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +    // モニターにローカル IPアドレスを表示する
削除しました。

2022-04-14 04:49 UTC, ryoimayoshi-schoomy requested changes
@syunsukefujisawa-schoomy 
再度1点追加したので確認お願いします。

2022-04-14 04:49 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +  <head>
@syunsukefujisawa-schoomy 
PAGE_TITLEをreplaceする方法は合っています！
その後[ココ](https://github.com/SchooMyDevelopment/schoomy_board/pull/1/files#diff-7356a7209b864aa046af34bd0131e0f4209d61d1f4aa7f5bfd9854a49751951aR104)
で `Wi-Fi LED ボタン` という同じ内容の文字列が2回ハードコードされているので、この文字列を変数として外に出しておいてください。

2022-04-18 01:56 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_LED.ino
> +  <head>
16行目で変数を宣言してそれを使うようにしました

2022-04-18 01:57 UTC, syunsukefujisawa-schoomy commented
16行目で変数を宣言してそれを使うようにしました

2022-04-18 02:35 UTC, ryoimayoshi-schoomy approved these changes
LGTM! マージします！

[共有事項]
・コメントに行数など詳細を記載するとコードが修正になった際にPRコメントと内容が乖離するので指摘コメントに続く形で対応内容を記載してください＾＾

2022-04-18 02:35 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_LED.ino
> +  <head>
対応内容確認しました。

2022-04-18 02:36 UTC, merged