create: wifi経由明るさセンサー
SchooMyDevelopment/schoomy_board pull request #2
Opened 2022-04-18 06:25 UTC by syunsukefujisawa-schoomy

wifi経由で明るさセンサーの値を表示させます。更新ボタンを押すことでセンサー値が更新されます。
LEDのプログラムをいじってつくりました。

2022-04-18 09:39 UTC, ryoimayoshi-schoomy requested changes
@syunsukefujisawa-schoomy 
今回はLED時の指摘事項が改善されているので問題もなさそうですが、1点記載しておいたので確認してください！

2022-04-18 09:39 UTC, ryoimayoshi-schoomy commented on black/sketch/wifi_BrightnessSenor.ino
> +const String button = R"rawliteral(
LEDのスケッチはボタンのONとOFFを切り替える必要があったので外に切り出してボタン押下時にhtmlをreplaceしていましたが今回はセンシングデータ以外は切り替える必要はないのでボタンは切り出さなくて良いです。

そしてボタン押下時の処理の中でボタン周りのHTMLをreplaceする必要もありません。

2022-04-19 02:19 UTC, naokiito-schoomy approved these changes
確認しました。
動作は問題ありませんでした！

2022-04-19 03:06 UTC, syunsukefujisawa-schoomy commented on black/sketch/wifi_BrightnessSenor.ino
> +const String button = R"rawliteral(
ボタン用変数の中身をBody用変数の中に移し、ボタンのreplaceの部分を消しました。

2022-04-19 04:19 UTC, SGA-ryo-imayoshi approved these changes
LGTM!

2022-04-19 04:21 UTC, SGA-ryo-imayoshi approved these changes

2022-04-19 04:55 UTC, ryoimayoshi-schoomy approved these changes

2022-04-19 04:56 UTC, merged